version: '2'
services:
  migrator:
    build: .
    command: npm run test
    links:
     - cassandra:cassandra
    volumes:
     - .:/home/app/src
     - /home/app/src/node_modules
  cassandra:
    image: cassandra:2.2.5
    ports:
      - "9042:9042"
